trigger:
  branches:
    include:
    - master
    - main
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: corvus-dotnet-github
      ref: feature/fix-scripted-build-release-issues

jobs:
- template: templates/build.and.release.scripted.yml@recommended_practices
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
    service_connection_github: $(Endjin_Service_Connection_GitHub)
    solution_to_build: $(Endjin_Solution_To_Build)
    postSpecs:
      - task: ArchiveFiles@2
        displayName: 'Archive KeepAlive Function App'
        inputs:
          rootFolderOrFile: 'Solutions/Corvus.AzureFunctionsKeepAlive.Host/bin/Release/netcoreapp3.1/'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/Release/Corvus.AzureFunctionsKeepAlive.Host.zip'
          replaceExistingArchive: true
    netSdkVersion: '6.x'
    additionalNetSdkVersions:
    - '3.x'
    compileTasksServiceConnection: endjin-acr-reader

